server:
  port: 8000
mysql:
  host: 127.0.0.1
  port: 3306
  database: vertx
  username: order
  password: order@123__
  charset: utf8mb4
  collation: utf8mb4_general_ci
  maxSize: 30
  reconnectAttempts: 3
  reconnectInterval: 1000
  poolName: v-pool
